
services:
  db:
    image: postgres:12
    container_name: my_backend_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_training_db
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

  api:
    build: .
    container_name: my_backend_api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/home_training_db
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

# bash
# docker ps
# docker exec -it 컨테이너 이름(my_backend_db) bash      exit 시 exit 명령
# psql -U postgres      
    # \du(사용자 목록 확인)   \l(데이터베이스 목록 확인) 명령 사용 가능
    # sql 스크립트 사용 가능   ALTER USER "user" WITH PASSWORD '1234';
    # exit 시 \q 명령
